version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - sudo yum install git -y 
      - sudo yum install pip -y
      - sudo yum install python -y
      - pip install -r requirements.txt
  build:
    commands:
      - python manage.py test
      - echo "Build complete"
